//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivingComplex.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int idNews { get; set; }
        public byte[] NewsPhoto { get; set; }
        public string NewsTitle { get; set; }
        public string NewsText { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<int> CreatorId { get; set; }
    
        public virtual Employers Employers { get; set; }
    }
}
