//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivingComplex.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        public int idTenant { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int GenderID { get; set; }
        public int Age { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public int FlatID { get; set; }
        public int TenantStatusID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> PassportSerial { get; set; }
        public Nullable<int> PassportNumber { get; set; }
        public long SNILS { get; set; }
        public Nullable<long> INN { get; set; }
    
        public virtual Flats Flats { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual TenantStatus TenantStatus { get; set; }
    }
}
